// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	ImageUrl string      `json:"image_url"`
}

type Invoice struct {
	ID         pgtype.UUID `json:"id"`
	CustomerID pgtype.UUID `json:"customer_id"`
	Amount     int32       `json:"amount"`
	Status     string      `json:"status"`
	Date       pgtype.Date `json:"date"`
}

type Revenue struct {
	Month   string `json:"month"`
	Revenue int32  `json:"revenue"`
}

type User struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
}
